/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RealEstateAgentsRouteImport } from './routes/real-estate-agents'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameIndexRouteImport } from './routes/$username.index'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedLogoutRouteImport } from './routes/_authenticated/logout'
import { Route as AuthenticatedBioRouteImport } from './routes/_authenticated/bio'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedFormsIndexRouteImport } from './routes/_authenticated/forms.index'
import { Route as AuthenticatedBioIndexRouteImport } from './routes/_authenticated/bio/index'
import { Route as AuthenticatedSystemUsersRouteImport } from './routes/_authenticated/system.users'
import { Route as AuthenticatedInvitesTokenRouteImport } from './routes/_authenticated/invites.$token'
import { Route as AuthenticatedFormsIdRouteImport } from './routes/_authenticated/forms/$id'
import { Route as AuthenticatedBioSettingsRouteImport } from './routes/_authenticated/bio/settings'
import { Route as AuthenticatedBioAppearanceRouteImport } from './routes/_authenticated/bio/appearance'
import { Route as AuthenticatedFormsIdIndexRouteImport } from './routes/_authenticated/forms/$id.index'
import { Route as AuthenticatedBioAppearanceIndexRouteImport } from './routes/_authenticated/bio/appearance/index'
import { Route as UsernameLinkLinkIdIndexRouteImport } from './routes/$username.link.$linkId.index'
import { Route as AuthenticatedFormsBuilderThreadIdRouteImport } from './routes/_authenticated/forms.builder.$threadId'
import { Route as AuthenticatedFormsIdSubmissionsRouteImport } from './routes/_authenticated/forms/$id.submissions'
import { Route as AuthenticatedFormsIdSettingsRouteImport } from './routes/_authenticated/forms/$id.settings'
import { Route as AuthenticatedDesignThemeThreadIdRouteImport } from './routes/_authenticated/design.theme.$threadId'
import { Route as AuthenticatedBioAppearanceThemesRouteImport } from './routes/_authenticated/bio/appearance/themes'
import { Route as AuthenticatedBioAppearanceCustomizeRouteImport } from './routes/_authenticated/bio/appearance/customize'
import { Route as AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRouteImport } from './routes/_authenticated/forms/$id.submissions.$submissionId.transcript'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateAgentsRoute = RealEstateAgentsRouteImport.update({
  id: '/real-estate-agents',
  path: '/real-estate-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogoutRoute = AuthenticatedLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBioRoute = AuthenticatedBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsIndexRoute = AuthenticatedFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBioIndexRoute = AuthenticatedBioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBioRoute,
} as any)
const AuthenticatedSystemUsersRoute =
  AuthenticatedSystemUsersRouteImport.update({
    id: '/system/users',
    path: '/system/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvitesTokenRoute =
  AuthenticatedInvitesTokenRouteImport.update({
    id: '/invites/$token',
    path: '/invites/$token',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormsIdRoute = AuthenticatedFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBioSettingsRoute =
  AuthenticatedBioSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedBioRoute,
  } as any)
const AuthenticatedBioAppearanceRoute =
  AuthenticatedBioAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedBioRoute,
  } as any)
const AuthenticatedFormsIdIndexRoute =
  AuthenticatedFormsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFormsIdRoute,
  } as any)
const AuthenticatedBioAppearanceIndexRoute =
  AuthenticatedBioAppearanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBioAppearanceRoute,
  } as any)
const UsernameLinkLinkIdIndexRoute = UsernameLinkLinkIdIndexRouteImport.update({
  id: '/$username/link/$linkId/',
  path: '/$username/link/$linkId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFormsBuilderThreadIdRoute =
  AuthenticatedFormsBuilderThreadIdRouteImport.update({
    id: '/forms/builder/$threadId',
    path: '/forms/builder/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormsIdSubmissionsRoute =
  AuthenticatedFormsIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedFormsIdRoute,
  } as any)
const AuthenticatedFormsIdSettingsRoute =
  AuthenticatedFormsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedFormsIdRoute,
  } as any)
const AuthenticatedDesignThemeThreadIdRoute =
  AuthenticatedDesignThemeThreadIdRouteImport.update({
    id: '/design/theme/$threadId',
    path: '/design/theme/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBioAppearanceThemesRoute =
  AuthenticatedBioAppearanceThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AuthenticatedBioAppearanceRoute,
  } as any)
const AuthenticatedBioAppearanceCustomizeRoute =
  AuthenticatedBioAppearanceCustomizeRouteImport.update({
    id: '/customize',
    path: '/customize',
    getParentRoute: () => AuthenticatedBioAppearanceRoute,
  } as any)
const AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute =
  AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRouteImport.update({
    id: '/$submissionId/transcript',
    path: '/$submissionId/transcript',
    getParentRoute: () => AuthenticatedFormsIdSubmissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate-agents': typeof RealEstateAgentsRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bio': typeof AuthenticatedBioRouteWithChildren
  '/logout': typeof AuthenticatedLogoutRoute
  '/team': typeof AuthenticatedTeamRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/$username/': typeof UsernameIndexRoute
  '/bio/appearance': typeof AuthenticatedBioAppearanceRouteWithChildren
  '/bio/settings': typeof AuthenticatedBioSettingsRoute
  '/forms/$id': typeof AuthenticatedFormsIdRouteWithChildren
  '/invites/$token': typeof AuthenticatedInvitesTokenRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/bio/': typeof AuthenticatedBioIndexRoute
  '/forms/': typeof AuthenticatedFormsIndexRoute
  '/bio/appearance/customize': typeof AuthenticatedBioAppearanceCustomizeRoute
  '/bio/appearance/themes': typeof AuthenticatedBioAppearanceThemesRoute
  '/design/theme/$threadId': typeof AuthenticatedDesignThemeThreadIdRoute
  '/forms/$id/settings': typeof AuthenticatedFormsIdSettingsRoute
  '/forms/$id/submissions': typeof AuthenticatedFormsIdSubmissionsRouteWithChildren
  '/forms/builder/$threadId': typeof AuthenticatedFormsBuilderThreadIdRoute
  '/$username/link/$linkId/': typeof UsernameLinkLinkIdIndexRoute
  '/bio/appearance/': typeof AuthenticatedBioAppearanceIndexRoute
  '/forms/$id/': typeof AuthenticatedFormsIdIndexRoute
  '/forms/$id/submissions/$submissionId/transcript': typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate-agents': typeof RealEstateAgentsRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/logout': typeof AuthenticatedLogoutRoute
  '/team': typeof AuthenticatedTeamRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/$username': typeof UsernameIndexRoute
  '/bio/settings': typeof AuthenticatedBioSettingsRoute
  '/invites/$token': typeof AuthenticatedInvitesTokenRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/bio': typeof AuthenticatedBioIndexRoute
  '/forms': typeof AuthenticatedFormsIndexRoute
  '/bio/appearance/customize': typeof AuthenticatedBioAppearanceCustomizeRoute
  '/bio/appearance/themes': typeof AuthenticatedBioAppearanceThemesRoute
  '/design/theme/$threadId': typeof AuthenticatedDesignThemeThreadIdRoute
  '/forms/$id/settings': typeof AuthenticatedFormsIdSettingsRoute
  '/forms/$id/submissions': typeof AuthenticatedFormsIdSubmissionsRouteWithChildren
  '/forms/builder/$threadId': typeof AuthenticatedFormsBuilderThreadIdRoute
  '/$username/link/$linkId': typeof UsernameLinkLinkIdIndexRoute
  '/bio/appearance': typeof AuthenticatedBioAppearanceIndexRoute
  '/forms/$id': typeof AuthenticatedFormsIdIndexRoute
  '/forms/$id/submissions/$submissionId/transcript': typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate-agents': typeof RealEstateAgentsRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bio': typeof AuthenticatedBioRouteWithChildren
  '/_authenticated/logout': typeof AuthenticatedLogoutRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/$username/': typeof UsernameIndexRoute
  '/_authenticated/bio/appearance': typeof AuthenticatedBioAppearanceRouteWithChildren
  '/_authenticated/bio/settings': typeof AuthenticatedBioSettingsRoute
  '/_authenticated/forms/$id': typeof AuthenticatedFormsIdRouteWithChildren
  '/_authenticated/invites/$token': typeof AuthenticatedInvitesTokenRoute
  '/_authenticated/system/users': typeof AuthenticatedSystemUsersRoute
  '/_authenticated/bio/': typeof AuthenticatedBioIndexRoute
  '/_authenticated/forms/': typeof AuthenticatedFormsIndexRoute
  '/_authenticated/bio/appearance/customize': typeof AuthenticatedBioAppearanceCustomizeRoute
  '/_authenticated/bio/appearance/themes': typeof AuthenticatedBioAppearanceThemesRoute
  '/_authenticated/design/theme/$threadId': typeof AuthenticatedDesignThemeThreadIdRoute
  '/_authenticated/forms/$id/settings': typeof AuthenticatedFormsIdSettingsRoute
  '/_authenticated/forms/$id/submissions': typeof AuthenticatedFormsIdSubmissionsRouteWithChildren
  '/_authenticated/forms/builder/$threadId': typeof AuthenticatedFormsBuilderThreadIdRoute
  '/$username/link/$linkId/': typeof UsernameLinkLinkIdIndexRoute
  '/_authenticated/bio/appearance/': typeof AuthenticatedBioAppearanceIndexRoute
  '/_authenticated/forms/$id/': typeof AuthenticatedFormsIdIndexRoute
  '/_authenticated/forms/$id/submissions/$submissionId/transcript': typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/onboarding'
    | '/privacy'
    | '/real-estate-agents'
    | '/signin'
    | '/terms'
    | '/analytics'
    | '/bio'
    | '/logout'
    | '/team'
    | '/upgrade'
    | '/$username/'
    | '/bio/appearance'
    | '/bio/settings'
    | '/forms/$id'
    | '/invites/$token'
    | '/system/users'
    | '/bio/'
    | '/forms/'
    | '/bio/appearance/customize'
    | '/bio/appearance/themes'
    | '/design/theme/$threadId'
    | '/forms/$id/settings'
    | '/forms/$id/submissions'
    | '/forms/builder/$threadId'
    | '/$username/link/$linkId/'
    | '/bio/appearance/'
    | '/forms/$id/'
    | '/forms/$id/submissions/$submissionId/transcript'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/onboarding'
    | '/privacy'
    | '/real-estate-agents'
    | '/signin'
    | '/terms'
    | '/analytics'
    | '/logout'
    | '/team'
    | '/upgrade'
    | '/$username'
    | '/bio/settings'
    | '/invites/$token'
    | '/system/users'
    | '/bio'
    | '/forms'
    | '/bio/appearance/customize'
    | '/bio/appearance/themes'
    | '/design/theme/$threadId'
    | '/forms/$id/settings'
    | '/forms/$id/submissions'
    | '/forms/builder/$threadId'
    | '/$username/link/$linkId'
    | '/bio/appearance'
    | '/forms/$id'
    | '/forms/$id/submissions/$submissionId/transcript'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/onboarding'
    | '/privacy'
    | '/real-estate-agents'
    | '/signin'
    | '/terms'
    | '/_authenticated/analytics'
    | '/_authenticated/bio'
    | '/_authenticated/logout'
    | '/_authenticated/team'
    | '/_authenticated/upgrade'
    | '/$username/'
    | '/_authenticated/bio/appearance'
    | '/_authenticated/bio/settings'
    | '/_authenticated/forms/$id'
    | '/_authenticated/invites/$token'
    | '/_authenticated/system/users'
    | '/_authenticated/bio/'
    | '/_authenticated/forms/'
    | '/_authenticated/bio/appearance/customize'
    | '/_authenticated/bio/appearance/themes'
    | '/_authenticated/design/theme/$threadId'
    | '/_authenticated/forms/$id/settings'
    | '/_authenticated/forms/$id/submissions'
    | '/_authenticated/forms/builder/$threadId'
    | '/$username/link/$linkId/'
    | '/_authenticated/bio/appearance/'
    | '/_authenticated/forms/$id/'
    | '/_authenticated/forms/$id/submissions/$submissionId/transcript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RealEstateAgentsRoute: typeof RealEstateAgentsRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
  UsernameLinkLinkIdIndexRoute: typeof UsernameLinkLinkIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate-agents': {
      id: '/real-estate-agents'
      path: '/real-estate-agents'
      fullPath: '/real-estate-agents'
      preLoaderRoute: typeof RealEstateAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logout': {
      id: '/_authenticated/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthenticatedLogoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio': {
      id: '/_authenticated/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof AuthenticatedBioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/': {
      id: '/_authenticated/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AuthenticatedFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio/': {
      id: '/_authenticated/bio/'
      path: '/'
      fullPath: '/bio/'
      preLoaderRoute: typeof AuthenticatedBioIndexRouteImport
      parentRoute: typeof AuthenticatedBioRoute
    }
    '/_authenticated/system/users': {
      id: '/_authenticated/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AuthenticatedSystemUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invites/$token': {
      id: '/_authenticated/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof AuthenticatedInvitesTokenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/$id': {
      id: '/_authenticated/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AuthenticatedFormsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio/settings': {
      id: '/_authenticated/bio/settings'
      path: '/settings'
      fullPath: '/bio/settings'
      preLoaderRoute: typeof AuthenticatedBioSettingsRouteImport
      parentRoute: typeof AuthenticatedBioRoute
    }
    '/_authenticated/bio/appearance': {
      id: '/_authenticated/bio/appearance'
      path: '/appearance'
      fullPath: '/bio/appearance'
      preLoaderRoute: typeof AuthenticatedBioAppearanceRouteImport
      parentRoute: typeof AuthenticatedBioRoute
    }
    '/_authenticated/forms/$id/': {
      id: '/_authenticated/forms/$id/'
      path: '/'
      fullPath: '/forms/$id/'
      preLoaderRoute: typeof AuthenticatedFormsIdIndexRouteImport
      parentRoute: typeof AuthenticatedFormsIdRoute
    }
    '/_authenticated/bio/appearance/': {
      id: '/_authenticated/bio/appearance/'
      path: '/'
      fullPath: '/bio/appearance/'
      preLoaderRoute: typeof AuthenticatedBioAppearanceIndexRouteImport
      parentRoute: typeof AuthenticatedBioAppearanceRoute
    }
    '/$username/link/$linkId/': {
      id: '/$username/link/$linkId/'
      path: '/$username/link/$linkId'
      fullPath: '/$username/link/$linkId/'
      preLoaderRoute: typeof UsernameLinkLinkIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forms/builder/$threadId': {
      id: '/_authenticated/forms/builder/$threadId'
      path: '/forms/builder/$threadId'
      fullPath: '/forms/builder/$threadId'
      preLoaderRoute: typeof AuthenticatedFormsBuilderThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/$id/submissions': {
      id: '/_authenticated/forms/$id/submissions'
      path: '/submissions'
      fullPath: '/forms/$id/submissions'
      preLoaderRoute: typeof AuthenticatedFormsIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedFormsIdRoute
    }
    '/_authenticated/forms/$id/settings': {
      id: '/_authenticated/forms/$id/settings'
      path: '/settings'
      fullPath: '/forms/$id/settings'
      preLoaderRoute: typeof AuthenticatedFormsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedFormsIdRoute
    }
    '/_authenticated/design/theme/$threadId': {
      id: '/_authenticated/design/theme/$threadId'
      path: '/design/theme/$threadId'
      fullPath: '/design/theme/$threadId'
      preLoaderRoute: typeof AuthenticatedDesignThemeThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio/appearance/themes': {
      id: '/_authenticated/bio/appearance/themes'
      path: '/themes'
      fullPath: '/bio/appearance/themes'
      preLoaderRoute: typeof AuthenticatedBioAppearanceThemesRouteImport
      parentRoute: typeof AuthenticatedBioAppearanceRoute
    }
    '/_authenticated/bio/appearance/customize': {
      id: '/_authenticated/bio/appearance/customize'
      path: '/customize'
      fullPath: '/bio/appearance/customize'
      preLoaderRoute: typeof AuthenticatedBioAppearanceCustomizeRouteImport
      parentRoute: typeof AuthenticatedBioAppearanceRoute
    }
    '/_authenticated/forms/$id/submissions/$submissionId/transcript': {
      id: '/_authenticated/forms/$id/submissions/$submissionId/transcript'
      path: '/$submissionId/transcript'
      fullPath: '/forms/$id/submissions/$submissionId/transcript'
      preLoaderRoute: typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRouteImport
      parentRoute: typeof AuthenticatedFormsIdSubmissionsRoute
    }
  }
}

interface AuthenticatedBioAppearanceRouteChildren {
  AuthenticatedBioAppearanceCustomizeRoute: typeof AuthenticatedBioAppearanceCustomizeRoute
  AuthenticatedBioAppearanceThemesRoute: typeof AuthenticatedBioAppearanceThemesRoute
  AuthenticatedBioAppearanceIndexRoute: typeof AuthenticatedBioAppearanceIndexRoute
}

const AuthenticatedBioAppearanceRouteChildren: AuthenticatedBioAppearanceRouteChildren =
  {
    AuthenticatedBioAppearanceCustomizeRoute:
      AuthenticatedBioAppearanceCustomizeRoute,
    AuthenticatedBioAppearanceThemesRoute:
      AuthenticatedBioAppearanceThemesRoute,
    AuthenticatedBioAppearanceIndexRoute: AuthenticatedBioAppearanceIndexRoute,
  }

const AuthenticatedBioAppearanceRouteWithChildren =
  AuthenticatedBioAppearanceRoute._addFileChildren(
    AuthenticatedBioAppearanceRouteChildren,
  )

interface AuthenticatedBioRouteChildren {
  AuthenticatedBioAppearanceRoute: typeof AuthenticatedBioAppearanceRouteWithChildren
  AuthenticatedBioSettingsRoute: typeof AuthenticatedBioSettingsRoute
  AuthenticatedBioIndexRoute: typeof AuthenticatedBioIndexRoute
}

const AuthenticatedBioRouteChildren: AuthenticatedBioRouteChildren = {
  AuthenticatedBioAppearanceRoute: AuthenticatedBioAppearanceRouteWithChildren,
  AuthenticatedBioSettingsRoute: AuthenticatedBioSettingsRoute,
  AuthenticatedBioIndexRoute: AuthenticatedBioIndexRoute,
}

const AuthenticatedBioRouteWithChildren =
  AuthenticatedBioRoute._addFileChildren(AuthenticatedBioRouteChildren)

interface AuthenticatedFormsIdSubmissionsRouteChildren {
  AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute: typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute
}

const AuthenticatedFormsIdSubmissionsRouteChildren: AuthenticatedFormsIdSubmissionsRouteChildren =
  {
    AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute:
      AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute,
  }

const AuthenticatedFormsIdSubmissionsRouteWithChildren =
  AuthenticatedFormsIdSubmissionsRoute._addFileChildren(
    AuthenticatedFormsIdSubmissionsRouteChildren,
  )

interface AuthenticatedFormsIdRouteChildren {
  AuthenticatedFormsIdSettingsRoute: typeof AuthenticatedFormsIdSettingsRoute
  AuthenticatedFormsIdSubmissionsRoute: typeof AuthenticatedFormsIdSubmissionsRouteWithChildren
  AuthenticatedFormsIdIndexRoute: typeof AuthenticatedFormsIdIndexRoute
}

const AuthenticatedFormsIdRouteChildren: AuthenticatedFormsIdRouteChildren = {
  AuthenticatedFormsIdSettingsRoute: AuthenticatedFormsIdSettingsRoute,
  AuthenticatedFormsIdSubmissionsRoute:
    AuthenticatedFormsIdSubmissionsRouteWithChildren,
  AuthenticatedFormsIdIndexRoute: AuthenticatedFormsIdIndexRoute,
}

const AuthenticatedFormsIdRouteWithChildren =
  AuthenticatedFormsIdRoute._addFileChildren(AuthenticatedFormsIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBioRoute: typeof AuthenticatedBioRouteWithChildren
  AuthenticatedLogoutRoute: typeof AuthenticatedLogoutRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedFormsIdRoute: typeof AuthenticatedFormsIdRouteWithChildren
  AuthenticatedInvitesTokenRoute: typeof AuthenticatedInvitesTokenRoute
  AuthenticatedSystemUsersRoute: typeof AuthenticatedSystemUsersRoute
  AuthenticatedFormsIndexRoute: typeof AuthenticatedFormsIndexRoute
  AuthenticatedDesignThemeThreadIdRoute: typeof AuthenticatedDesignThemeThreadIdRoute
  AuthenticatedFormsBuilderThreadIdRoute: typeof AuthenticatedFormsBuilderThreadIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBioRoute: AuthenticatedBioRouteWithChildren,
  AuthenticatedLogoutRoute: AuthenticatedLogoutRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedFormsIdRoute: AuthenticatedFormsIdRouteWithChildren,
  AuthenticatedInvitesTokenRoute: AuthenticatedInvitesTokenRoute,
  AuthenticatedSystemUsersRoute: AuthenticatedSystemUsersRoute,
  AuthenticatedFormsIndexRoute: AuthenticatedFormsIndexRoute,
  AuthenticatedDesignThemeThreadIdRoute: AuthenticatedDesignThemeThreadIdRoute,
  AuthenticatedFormsBuilderThreadIdRoute:
    AuthenticatedFormsBuilderThreadIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RealEstateAgentsRoute: RealEstateAgentsRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  UsernameIndexRoute: UsernameIndexRoute,
  UsernameLinkLinkIdIndexRoute: UsernameLinkLinkIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
