/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RealEstateAgentsRouteImport } from './routes/real-estate-agents'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameIndexRouteImport } from './routes/$username.index'
import { Route as SigninCompleteRouteImport } from './routes/signin.complete'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedBioRouteImport } from './routes/_authenticated/bio'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedFormsIndexRouteImport } from './routes/_authenticated/forms.index'
import { Route as AuthenticatedBioIndexRouteImport } from './routes/_authenticated/bio/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedFormsIdRouteImport } from './routes/_authenticated/forms/$id'
import { Route as AuthenticatedBioSettingsRouteImport } from './routes/_authenticated/bio/settings'
import { Route as AuthenticatedBioAppearanceRouteImport } from './routes/_authenticated/bio/appearance'
import { Route as AuthenticatedFormsIdIndexRouteImport } from './routes/_authenticated/forms/$id.index'
import { Route as AuthenticatedBioAppearanceIndexRouteImport } from './routes/_authenticated/bio/appearance/index'
import { Route as UsernameLinkLinkIdIndexRouteImport } from './routes/$username.link.$linkId.index'
import { Route as AuthenticatedFormsBuilderThreadIdRouteImport } from './routes/_authenticated/forms.builder.$threadId'
import { Route as AuthenticatedFormsIdSubmissionsRouteImport } from './routes/_authenticated/forms/$id.submissions'
import { Route as AuthenticatedFormsIdSettingsRouteImport } from './routes/_authenticated/forms/$id.settings'
import { Route as AuthenticatedDesignThemeThreadIdRouteImport } from './routes/_authenticated/design.theme.$threadId'
import { Route as AuthenticatedBioAppearanceThemesRouteImport } from './routes/_authenticated/bio/appearance/themes'
import { Route as AuthenticatedBioAppearanceCustomizeRouteImport } from './routes/_authenticated/bio/appearance/customize'
import { Route as AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRouteImport } from './routes/_authenticated/forms/$id.submissions.$submissionId.transcript'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateAgentsRoute = RealEstateAgentsRouteImport.update({
  id: '/real-estate-agents',
  path: '/real-estate-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninCompleteRoute = SigninCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => SigninRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBioRoute = AuthenticatedBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsIndexRoute = AuthenticatedFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBioIndexRoute = AuthenticatedBioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFormsIdRoute = AuthenticatedFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBioSettingsRoute =
  AuthenticatedBioSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedBioRoute,
  } as any)
const AuthenticatedBioAppearanceRoute =
  AuthenticatedBioAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedBioRoute,
  } as any)
const AuthenticatedFormsIdIndexRoute =
  AuthenticatedFormsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFormsIdRoute,
  } as any)
const AuthenticatedBioAppearanceIndexRoute =
  AuthenticatedBioAppearanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBioAppearanceRoute,
  } as any)
const UsernameLinkLinkIdIndexRoute = UsernameLinkLinkIdIndexRouteImport.update({
  id: '/$username/link/$linkId/',
  path: '/$username/link/$linkId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFormsBuilderThreadIdRoute =
  AuthenticatedFormsBuilderThreadIdRouteImport.update({
    id: '/forms/builder/$threadId',
    path: '/forms/builder/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormsIdSubmissionsRoute =
  AuthenticatedFormsIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedFormsIdRoute,
  } as any)
const AuthenticatedFormsIdSettingsRoute =
  AuthenticatedFormsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedFormsIdRoute,
  } as any)
const AuthenticatedDesignThemeThreadIdRoute =
  AuthenticatedDesignThemeThreadIdRouteImport.update({
    id: '/design/theme/$threadId',
    path: '/design/theme/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBioAppearanceThemesRoute =
  AuthenticatedBioAppearanceThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AuthenticatedBioAppearanceRoute,
  } as any)
const AuthenticatedBioAppearanceCustomizeRoute =
  AuthenticatedBioAppearanceCustomizeRouteImport.update({
    id: '/customize',
    path: '/customize',
    getParentRoute: () => AuthenticatedBioAppearanceRoute,
  } as any)
const AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute =
  AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRouteImport.update({
    id: '/$submissionId/transcript',
    path: '/$submissionId/transcript',
    getParentRoute: () => AuthenticatedFormsIdSubmissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/real-estate-agents': typeof RealEstateAgentsRoute
  '/signin': typeof SigninRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bio': typeof AuthenticatedBioRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/signin/complete': typeof SigninCompleteRoute
  '/$username/': typeof UsernameIndexRoute
  '/bio/appearance': typeof AuthenticatedBioAppearanceRouteWithChildren
  '/bio/settings': typeof AuthenticatedBioSettingsRoute
  '/forms/$id': typeof AuthenticatedFormsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bio/': typeof AuthenticatedBioIndexRoute
  '/forms/': typeof AuthenticatedFormsIndexRoute
  '/bio/appearance/customize': typeof AuthenticatedBioAppearanceCustomizeRoute
  '/bio/appearance/themes': typeof AuthenticatedBioAppearanceThemesRoute
  '/design/theme/$threadId': typeof AuthenticatedDesignThemeThreadIdRoute
  '/forms/$id/settings': typeof AuthenticatedFormsIdSettingsRoute
  '/forms/$id/submissions': typeof AuthenticatedFormsIdSubmissionsRouteWithChildren
  '/forms/builder/$threadId': typeof AuthenticatedFormsBuilderThreadIdRoute
  '/$username/link/$linkId/': typeof UsernameLinkLinkIdIndexRoute
  '/bio/appearance/': typeof AuthenticatedBioAppearanceIndexRoute
  '/forms/$id/': typeof AuthenticatedFormsIdIndexRoute
  '/forms/$id/submissions/$submissionId/transcript': typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/real-estate-agents': typeof RealEstateAgentsRoute
  '/signin': typeof SigninRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/signin/complete': typeof SigninCompleteRoute
  '/$username': typeof UsernameIndexRoute
  '/bio/settings': typeof AuthenticatedBioSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bio': typeof AuthenticatedBioIndexRoute
  '/forms': typeof AuthenticatedFormsIndexRoute
  '/bio/appearance/customize': typeof AuthenticatedBioAppearanceCustomizeRoute
  '/bio/appearance/themes': typeof AuthenticatedBioAppearanceThemesRoute
  '/design/theme/$threadId': typeof AuthenticatedDesignThemeThreadIdRoute
  '/forms/$id/settings': typeof AuthenticatedFormsIdSettingsRoute
  '/forms/$id/submissions': typeof AuthenticatedFormsIdSubmissionsRouteWithChildren
  '/forms/builder/$threadId': typeof AuthenticatedFormsBuilderThreadIdRoute
  '/$username/link/$linkId': typeof UsernameLinkLinkIdIndexRoute
  '/bio/appearance': typeof AuthenticatedBioAppearanceIndexRoute
  '/forms/$id': typeof AuthenticatedFormsIdIndexRoute
  '/forms/$id/submissions/$submissionId/transcript': typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/real-estate-agents': typeof RealEstateAgentsRoute
  '/signin': typeof SigninRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bio': typeof AuthenticatedBioRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/signin/complete': typeof SigninCompleteRoute
  '/$username/': typeof UsernameIndexRoute
  '/_authenticated/bio/appearance': typeof AuthenticatedBioAppearanceRouteWithChildren
  '/_authenticated/bio/settings': typeof AuthenticatedBioSettingsRoute
  '/_authenticated/forms/$id': typeof AuthenticatedFormsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/bio/': typeof AuthenticatedBioIndexRoute
  '/_authenticated/forms/': typeof AuthenticatedFormsIndexRoute
  '/_authenticated/bio/appearance/customize': typeof AuthenticatedBioAppearanceCustomizeRoute
  '/_authenticated/bio/appearance/themes': typeof AuthenticatedBioAppearanceThemesRoute
  '/_authenticated/design/theme/$threadId': typeof AuthenticatedDesignThemeThreadIdRoute
  '/_authenticated/forms/$id/settings': typeof AuthenticatedFormsIdSettingsRoute
  '/_authenticated/forms/$id/submissions': typeof AuthenticatedFormsIdSubmissionsRouteWithChildren
  '/_authenticated/forms/builder/$threadId': typeof AuthenticatedFormsBuilderThreadIdRoute
  '/$username/link/$linkId/': typeof UsernameLinkLinkIdIndexRoute
  '/_authenticated/bio/appearance/': typeof AuthenticatedBioAppearanceIndexRoute
  '/_authenticated/forms/$id/': typeof AuthenticatedFormsIdIndexRoute
  '/_authenticated/forms/$id/submissions/$submissionId/transcript': typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/real-estate-agents'
    | '/signin'
    | '/analytics'
    | '/bio'
    | '/onboarding'
    | '/upgrade'
    | '/signin/complete'
    | '/$username/'
    | '/bio/appearance'
    | '/bio/settings'
    | '/forms/$id'
    | '/api/auth/$'
    | '/bio/'
    | '/forms/'
    | '/bio/appearance/customize'
    | '/bio/appearance/themes'
    | '/design/theme/$threadId'
    | '/forms/$id/settings'
    | '/forms/$id/submissions'
    | '/forms/builder/$threadId'
    | '/$username/link/$linkId/'
    | '/bio/appearance/'
    | '/forms/$id/'
    | '/forms/$id/submissions/$submissionId/transcript'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/real-estate-agents'
    | '/signin'
    | '/analytics'
    | '/onboarding'
    | '/upgrade'
    | '/signin/complete'
    | '/$username'
    | '/bio/settings'
    | '/api/auth/$'
    | '/bio'
    | '/forms'
    | '/bio/appearance/customize'
    | '/bio/appearance/themes'
    | '/design/theme/$threadId'
    | '/forms/$id/settings'
    | '/forms/$id/submissions'
    | '/forms/builder/$threadId'
    | '/$username/link/$linkId'
    | '/bio/appearance'
    | '/forms/$id'
    | '/forms/$id/submissions/$submissionId/transcript'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logout'
    | '/real-estate-agents'
    | '/signin'
    | '/_authenticated/analytics'
    | '/_authenticated/bio'
    | '/_authenticated/onboarding'
    | '/_authenticated/upgrade'
    | '/signin/complete'
    | '/$username/'
    | '/_authenticated/bio/appearance'
    | '/_authenticated/bio/settings'
    | '/_authenticated/forms/$id'
    | '/api/auth/$'
    | '/_authenticated/bio/'
    | '/_authenticated/forms/'
    | '/_authenticated/bio/appearance/customize'
    | '/_authenticated/bio/appearance/themes'
    | '/_authenticated/design/theme/$threadId'
    | '/_authenticated/forms/$id/settings'
    | '/_authenticated/forms/$id/submissions'
    | '/_authenticated/forms/builder/$threadId'
    | '/$username/link/$linkId/'
    | '/_authenticated/bio/appearance/'
    | '/_authenticated/forms/$id/'
    | '/_authenticated/forms/$id/submissions/$submissionId/transcript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  RealEstateAgentsRoute: typeof RealEstateAgentsRoute
  SigninRoute: typeof SigninRouteWithChildren
  UsernameIndexRoute: typeof UsernameIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  UsernameLinkLinkIdIndexRoute: typeof UsernameLinkLinkIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate-agents': {
      id: '/real-estate-agents'
      path: '/real-estate-agents'
      fullPath: '/real-estate-agents'
      preLoaderRoute: typeof RealEstateAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/complete': {
      id: '/signin/complete'
      path: '/complete'
      fullPath: '/signin/complete'
      preLoaderRoute: typeof SigninCompleteRouteImport
      parentRoute: typeof SigninRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio': {
      id: '/_authenticated/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof AuthenticatedBioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/': {
      id: '/_authenticated/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AuthenticatedFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio/': {
      id: '/_authenticated/bio/'
      path: '/'
      fullPath: '/bio/'
      preLoaderRoute: typeof AuthenticatedBioIndexRouteImport
      parentRoute: typeof AuthenticatedBioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forms/$id': {
      id: '/_authenticated/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AuthenticatedFormsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio/settings': {
      id: '/_authenticated/bio/settings'
      path: '/settings'
      fullPath: '/bio/settings'
      preLoaderRoute: typeof AuthenticatedBioSettingsRouteImport
      parentRoute: typeof AuthenticatedBioRoute
    }
    '/_authenticated/bio/appearance': {
      id: '/_authenticated/bio/appearance'
      path: '/appearance'
      fullPath: '/bio/appearance'
      preLoaderRoute: typeof AuthenticatedBioAppearanceRouteImport
      parentRoute: typeof AuthenticatedBioRoute
    }
    '/_authenticated/forms/$id/': {
      id: '/_authenticated/forms/$id/'
      path: '/'
      fullPath: '/forms/$id/'
      preLoaderRoute: typeof AuthenticatedFormsIdIndexRouteImport
      parentRoute: typeof AuthenticatedFormsIdRoute
    }
    '/_authenticated/bio/appearance/': {
      id: '/_authenticated/bio/appearance/'
      path: '/'
      fullPath: '/bio/appearance/'
      preLoaderRoute: typeof AuthenticatedBioAppearanceIndexRouteImport
      parentRoute: typeof AuthenticatedBioAppearanceRoute
    }
    '/$username/link/$linkId/': {
      id: '/$username/link/$linkId/'
      path: '/$username/link/$linkId'
      fullPath: '/$username/link/$linkId/'
      preLoaderRoute: typeof UsernameLinkLinkIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forms/builder/$threadId': {
      id: '/_authenticated/forms/builder/$threadId'
      path: '/forms/builder/$threadId'
      fullPath: '/forms/builder/$threadId'
      preLoaderRoute: typeof AuthenticatedFormsBuilderThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/$id/submissions': {
      id: '/_authenticated/forms/$id/submissions'
      path: '/submissions'
      fullPath: '/forms/$id/submissions'
      preLoaderRoute: typeof AuthenticatedFormsIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedFormsIdRoute
    }
    '/_authenticated/forms/$id/settings': {
      id: '/_authenticated/forms/$id/settings'
      path: '/settings'
      fullPath: '/forms/$id/settings'
      preLoaderRoute: typeof AuthenticatedFormsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedFormsIdRoute
    }
    '/_authenticated/design/theme/$threadId': {
      id: '/_authenticated/design/theme/$threadId'
      path: '/design/theme/$threadId'
      fullPath: '/design/theme/$threadId'
      preLoaderRoute: typeof AuthenticatedDesignThemeThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio/appearance/themes': {
      id: '/_authenticated/bio/appearance/themes'
      path: '/themes'
      fullPath: '/bio/appearance/themes'
      preLoaderRoute: typeof AuthenticatedBioAppearanceThemesRouteImport
      parentRoute: typeof AuthenticatedBioAppearanceRoute
    }
    '/_authenticated/bio/appearance/customize': {
      id: '/_authenticated/bio/appearance/customize'
      path: '/customize'
      fullPath: '/bio/appearance/customize'
      preLoaderRoute: typeof AuthenticatedBioAppearanceCustomizeRouteImport
      parentRoute: typeof AuthenticatedBioAppearanceRoute
    }
    '/_authenticated/forms/$id/submissions/$submissionId/transcript': {
      id: '/_authenticated/forms/$id/submissions/$submissionId/transcript'
      path: '/$submissionId/transcript'
      fullPath: '/forms/$id/submissions/$submissionId/transcript'
      preLoaderRoute: typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRouteImport
      parentRoute: typeof AuthenticatedFormsIdSubmissionsRoute
    }
  }
}

interface AuthenticatedBioAppearanceRouteChildren {
  AuthenticatedBioAppearanceCustomizeRoute: typeof AuthenticatedBioAppearanceCustomizeRoute
  AuthenticatedBioAppearanceThemesRoute: typeof AuthenticatedBioAppearanceThemesRoute
  AuthenticatedBioAppearanceIndexRoute: typeof AuthenticatedBioAppearanceIndexRoute
}

const AuthenticatedBioAppearanceRouteChildren: AuthenticatedBioAppearanceRouteChildren =
  {
    AuthenticatedBioAppearanceCustomizeRoute:
      AuthenticatedBioAppearanceCustomizeRoute,
    AuthenticatedBioAppearanceThemesRoute:
      AuthenticatedBioAppearanceThemesRoute,
    AuthenticatedBioAppearanceIndexRoute: AuthenticatedBioAppearanceIndexRoute,
  }

const AuthenticatedBioAppearanceRouteWithChildren =
  AuthenticatedBioAppearanceRoute._addFileChildren(
    AuthenticatedBioAppearanceRouteChildren,
  )

interface AuthenticatedBioRouteChildren {
  AuthenticatedBioAppearanceRoute: typeof AuthenticatedBioAppearanceRouteWithChildren
  AuthenticatedBioSettingsRoute: typeof AuthenticatedBioSettingsRoute
  AuthenticatedBioIndexRoute: typeof AuthenticatedBioIndexRoute
}

const AuthenticatedBioRouteChildren: AuthenticatedBioRouteChildren = {
  AuthenticatedBioAppearanceRoute: AuthenticatedBioAppearanceRouteWithChildren,
  AuthenticatedBioSettingsRoute: AuthenticatedBioSettingsRoute,
  AuthenticatedBioIndexRoute: AuthenticatedBioIndexRoute,
}

const AuthenticatedBioRouteWithChildren =
  AuthenticatedBioRoute._addFileChildren(AuthenticatedBioRouteChildren)

interface AuthenticatedFormsIdSubmissionsRouteChildren {
  AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute: typeof AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute
}

const AuthenticatedFormsIdSubmissionsRouteChildren: AuthenticatedFormsIdSubmissionsRouteChildren =
  {
    AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute:
      AuthenticatedFormsIdSubmissionsSubmissionIdTranscriptRoute,
  }

const AuthenticatedFormsIdSubmissionsRouteWithChildren =
  AuthenticatedFormsIdSubmissionsRoute._addFileChildren(
    AuthenticatedFormsIdSubmissionsRouteChildren,
  )

interface AuthenticatedFormsIdRouteChildren {
  AuthenticatedFormsIdSettingsRoute: typeof AuthenticatedFormsIdSettingsRoute
  AuthenticatedFormsIdSubmissionsRoute: typeof AuthenticatedFormsIdSubmissionsRouteWithChildren
  AuthenticatedFormsIdIndexRoute: typeof AuthenticatedFormsIdIndexRoute
}

const AuthenticatedFormsIdRouteChildren: AuthenticatedFormsIdRouteChildren = {
  AuthenticatedFormsIdSettingsRoute: AuthenticatedFormsIdSettingsRoute,
  AuthenticatedFormsIdSubmissionsRoute:
    AuthenticatedFormsIdSubmissionsRouteWithChildren,
  AuthenticatedFormsIdIndexRoute: AuthenticatedFormsIdIndexRoute,
}

const AuthenticatedFormsIdRouteWithChildren =
  AuthenticatedFormsIdRoute._addFileChildren(AuthenticatedFormsIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBioRoute: typeof AuthenticatedBioRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedFormsIdRoute: typeof AuthenticatedFormsIdRouteWithChildren
  AuthenticatedFormsIndexRoute: typeof AuthenticatedFormsIndexRoute
  AuthenticatedDesignThemeThreadIdRoute: typeof AuthenticatedDesignThemeThreadIdRoute
  AuthenticatedFormsBuilderThreadIdRoute: typeof AuthenticatedFormsBuilderThreadIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBioRoute: AuthenticatedBioRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedFormsIdRoute: AuthenticatedFormsIdRouteWithChildren,
  AuthenticatedFormsIndexRoute: AuthenticatedFormsIndexRoute,
  AuthenticatedDesignThemeThreadIdRoute: AuthenticatedDesignThemeThreadIdRoute,
  AuthenticatedFormsBuilderThreadIdRoute:
    AuthenticatedFormsBuilderThreadIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SigninRouteChildren {
  SigninCompleteRoute: typeof SigninCompleteRoute
}

const SigninRouteChildren: SigninRouteChildren = {
  SigninCompleteRoute: SigninCompleteRoute,
}

const SigninRouteWithChildren =
  SigninRoute._addFileChildren(SigninRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  RealEstateAgentsRoute: RealEstateAgentsRoute,
  SigninRoute: SigninRouteWithChildren,
  UsernameIndexRoute: UsernameIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  UsernameLinkLinkIdIndexRoute: UsernameLinkLinkIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
