name: Tinybird CI

on:
  pull_request:
    paths:
      - "tinybird.config.*"
      - "tinybird.json"
      - "**/*.ts"

env:
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  tinybird:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Create preview branch
        run: pnpm run tinybird:preview
